### ISSUE TITLE
support underscore for properties

### ISSUE THREAD

**Issue by colorcube** [libgraviton/rql-parser#14]
I think RQL allow properties with underscores like this

eq(my_property, 5)

The lexer doesn' t parse that.

I modified the src/SubLexer/StringSubLexer.php to make that work and just found out somebody else did the exact same thing:

https://github.com/Datazource/rql-parser/commit/7e0d81078dd97555a2af56855f95be736f16b561

**Comment by narcoticfresh** [comment]
quite old, assuming not current..
