### ISSUE TITLE
Support nested field queries.

### ISSUE THREAD

**Issue by amanangira** [libgraviton/rql-parser#16]
Consider an object
`{ "id" : 1231321, "amount" : { "total" : 299, "currency" : "USD" } }`, how do I query for `amount.total=299`?

**Comment by mrix** [comment]
`eq(amount%2Etotal,299)`

**Comment by amanangira** [comment]
I am afraid I have tried that already but its not working. No errors, simply returns the entire data set.

**Comment by mrix** [comment]
Probably the problem is in the query-to-filter transformation. This repository is the parser only. The query I wrote above looks correct.

**Comment by amanangira** [comment]
Can you please tell what library is being used for query-to-filter.
