### ISSUE TITLE
Merge with php-rql-parser and dependencies

### ISSUE THREAD

**Issue by dontub** [libgraviton/rql-parser#17]
We are using rql-parser via [andreas-glaser/doctrine-rql](https://github.com/andreas-glaser/doctrine-rql). I'm afraid in case rql-parser is merged with php-rql-parser as hold out in the last release notes this would add various MongoDB related dependencies.

**Comment by narcoticfresh** [comment]
@dontub 
OK; acknowledged.. if we do a merge, we will see how we do that without introducing new dependencies for people that don't use MongoDB.. actually, out php-rql-parser should be split into something that is mongodb specific and then the remaining things can be merged into libgraviton/rql-parser..

Thanks for your input..
